config/routes.rb
CacheProd::Application.routes.draw do
  resources :readers

  resources :document_groups do
    collection do
      get :tree
    end
  end

  get "welcome/index"
  resources :documents do
    member do
      get :details
    end
  end

  get "errors_messages/error400"
  get "errors_messages/error401"
  get "errors_messages/error402"

  root 'welcome#index'

  

end

app/models/document.rb
require 'digest/md5'

class Document < ActiveRecord::Base
  belongs_to :document_group, touch: true
  has_and_belongs_to_many :readers

  def checksum
    sleep 2
    Digest::MD5.hexdigest(self.title + cache_key)
  end
end

app/models/document_group.rb
class DocumentGroup < ActiveRecord::Base
  has_many :documents
  has_many :readers, through: :documents
end

app/models/reader.rb
class Reader < ActiveRecord::Base
  has_and_belongs_to_many :documents#, touch: true

  def checksum
    sleep 0.2
    Digest::MD5.hexdigest(self.name + cache_key)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/document_groups_controller.rb
class DocumentGroupsController < ApplicationController
  before_action :set_document_group, only: [:show, :edit, :update, :destroy]

  def index
    @document_groups = DocumentGroup.all
  end

  def tree
    @document_groups = DocumentGroup.all
  end

  def show
  end

  def new
    @document_group = DocumentGroup.new
  end

  def edit
  end

  def create
    @document_group = DocumentGroup.new(document_group_params)

    respond_to do |format|
      if @document_group.save
        format.html { redirect_to @document_group, notice: 'Document group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document_group }
      else
        format.html { render action: 'new' }
        format.json { render json: @document_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @document_group.update(document_group_params)
        format.html { redirect_to @document_group, notice: 'Document group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @document_group.destroy
    respond_to do |format|
      format.html { redirect_to document_groups_url }
      format.json { head :no_content }
    end
  end

  private
    def set_document_group
      @document_group = DocumentGroup.find(params[:id])
    end

    def document_group_params
      params.require(:document_group).permit(:name)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :details, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  def details
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :content, :document_group_id)
    end
end

app/controllers/errors_messages_controller.rb
class ErrorsMessagesController < ApplicationController
  caches_page :error401

  def error400
    sleep 2
  end

  def error401
    sleep 2
  end

  def error402
    sleep 2
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  before_action :set_reader, only: [:show, :edit, :update, :destroy]

  # GET /readers
  # GET /readers.json
  def index
    @readers = Reader.all
  end

  # GET /readers/1
  # GET /readers/1.json
  def show
  end

  # GET /readers/new
  def new
    @reader = Reader.new
  end

  # GET /readers/1/edit
  def edit
  end

  # POST /readers
  # POST /readers.json
  def create
    @reader = Reader.new(reader_params)

    respond_to do |format|
      if @reader.save
        format.html { redirect_to @reader, notice: 'Reader was successfully created.' }
        format.json { render action: 'show', status: :created, location: @reader }
      else
        format.html { render action: 'new' }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readers/1
  # PATCH/PUT /readers/1.json
  def update
    respond_to do |format|
      if @reader.update(reader_params)
        format.html { redirect_to @reader, notice: 'Reader was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readers/1
  # DELETE /readers/1.json
  def destroy
    @reader.destroy
    respond_to do |format|
      format.html { redirect_to readers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reader
      @reader = Reader.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reader_params
      params.require(:reader).permit(:name, document_ids: [])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/document_groups_helper.rb
module DocumentGroupsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/errors_messages_helper.rb
module ErrorsMessagesHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/document_groups/_form.html.erb
<%= form_for(@document_group) do |f| %>
  <% if @document_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document_group.errors.count, "error") %> prohibited this document_group from being saved:</h2>

      <ul>
      <% @document_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/document_groups/edit.html.erb
<h1>Editing document_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @document_group %> |
<%= link_to 'Back', document_groups_path %>

app/views/document_groups/index.html.erb
<h1>Listing document_groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @document_groups.each do |document_group| %>
      <tr>
        <td><%= document_group.name %></td>
        <td><%= link_to 'Show', document_group %></td>
        <td><%= link_to 'Edit', edit_document_group_path(document_group) %></td>
        <td><%= link_to 'Destroy', document_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document group', new_document_group_path %>

app/views/document_groups/new.html.erb
<h1>New document_group</h1>

<%= render 'form' %>

<%= link_to 'Back', document_groups_path %>

app/views/document_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document_group.name %>
</p>

<%= link_to 'Edit', edit_document_group_path(@document_group) %> |
<%= link_to 'Back', document_groups_path %>

app/views/document_groups/tree.html.erb
<div id="document-groups-tree">
  <% @document_groups.each do |document_group| %>
      <% cache([document_group, document_group.documents, document_group.readers]) do %>
          <h1>
            <%= document_group.name %>
          </h1>
          <%= render document_group.documents %>
      <% end %>
  <% end %>  
</div>

app/views/documents/_document.erb
<% cache([document, document.readers]) do %>
    <h2>
      <%= document.title %>
      <%= render document.readers %>
    </h2>
<% end %>

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.collection_select(:document_group_id, DocumentGroup.all, :id, :name) %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/details.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Checksum very difficult to calculate:</strong>
  <% cache(@document) do %>
    <%= @document.checksum %>
  <% end %>
</p>

<p>
  <strong>Cache key:</strong>
  <%= @document.cache_key %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><%= truncate(document.content, length: 70) %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Details', details_document_path(document) %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @document.content %>
</p>

<p>
  <strong>Group:</strong>
  <%= @document.document_group.name %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/errors_messages/error400.html.erb
<h1>ErrorsMessages#error400</h1>
<p>Find me in app/views/errors_messages/error400.html.erb</p>

app/views/errors_messages/error401.html.erb
<h1>ErrorsMessages#error401</h1>
<p>Find me in app/views/errors_messages/error401.html.erb</p>

app/views/errors_messages/error402.html.erb
<h1>ErrorsMessages#error402</h1>
<p>Find me in app/views/errors_messages/error402.html.erb</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%= link_to 'Documents', documents_path, class: 'navbar-brand' %>
<%= link_to 'Document Groups', document_groups_path, class: 'navbar-brand' %>
<%= link_to 'Document Groups Tree', tree_document_groups_path, class: 'navbar-brand' %>
<%= link_to 'Readers', readers_path, class: 'navbar-brand' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title><%= content_for?(:title) ? yield(:title) : 'Cache matters! - Coder\'s Lab' %></title>
    <meta name='description' content='<%= content_for?(:description) ? yield(:description) : 'Cache Prod' %>'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role='main'>
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/readers/_form.html.erb
<%= form_for(@reader) do |f| %>
  <% if @reader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reader.errors.count, "error") %> prohibited this reader from being saved:</h2>

      <ul>
      <% @reader.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :document_ids %><br>
    <%= f.select :document_ids, Document.all.map { |d| [d.title, d.id] }, {}, multiple: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readers/_reader.html.erb
<% cache(reader) do %>
    <h3>
      <%= reader.name %>
      <%= reader.checksum %>
    </h3>
<% end %>

app/views/readers/edit.html.erb
<h1>Editing reader</h1>

<%= render 'form' %>

<%= link_to 'Show', @reader %> |
<%= link_to 'Back', readers_path %>

app/views/readers/index.html.erb
<h1>Listing readers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Documents</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @readers.each do |reader| %>
      <tr>
        <td><%= reader.name %></td>
        <td><%= reader.documents.count %></td>
        <td><%= link_to 'Show', reader %></td>
        <td><%= link_to 'Edit', edit_reader_path(reader) %></td>
        <td><%= link_to 'Destroy', reader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reader', new_reader_path %>

app/views/readers/new.html.erb
<h1>New reader</h1>

<%= render 'form' %>

<%= link_to 'Back', readers_path %>

app/views/readers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reader.name %>
</p>

<p>
  <strong>Documents:</strong>
  <%= @reader.documents.count %>
</p>

<%= link_to 'Edit', edit_reader_path(@reader) %> |
<%= link_to 'Back', readers_path %>

app/views/welcome/index.html.erb
<img src="http://www.coderslab.pl/img/logo.png">
<h3 class="text-center">Welcome!</h3>